= AsciiDocとMS Officeの比較

ここでは、エンタープライズシステムの設計書を作成・保守するツールとしてAsciiDocとMS Officeを比較します。

多くのエンタープライズシステムでは、設計書はMS Office(Word、Excel、PowerPoint)で作成されます。しかしMS Officeで作成された設計書は変更履歴の視認性や課題があります。

AsciiDocは2002年に開発された軽量マークアップ言語で、現在OSSの文書作成で広く使用されています。

以降では先ずAsciiDocの概要を説明し、その後にAsciiDocのMS Officeに対する長所・短所を挙げます。


== AsciiDocの概説

AsciiDocで書いた文書はテキストファイルとして保存します。ファイルの拡張子はadocです。テキストファイルなのでメモ帳などのテキストエディタで編集が可能です。Visual Studio CodeなどAsciiDocをサポートするテキストエディタでは、シンタックスハイライトやプレビュー機能が使用できます。

以下に設計書作成で使用頻度の高い構文を挙げます。

* 見出し
* 箇条書き
* 表
** CSVインクルード
* シンタックスハイライト






== AsciiDocの長所

=== 差分の視認が容易

AsciiDocは一般的なテキストエディタを使えば2つのバージョン間の差分はを行単位で視認できる。
またAsciiDocでは作図もテキストで行うため、図の差分も視認も容易である。


=== 変更のマージが容易


Git等のバージョン管理ツールを使用すると、1つのファイルに2人が異なる変更を同時に加えたとしても、変更箇所が行単位に異なっていれば自動的にマージされる。

履歴が見やすい


複数人で並行開発しやすい


=== 体裁の平仄を取りやすい

AsciiDocでは、個別のファイルでフォントや色の指定を行
Office文書の

特に作図は

設計情報　テキスト　体裁の指定が分離されているため

=== 文字列の検索・置換が容易

文字列の複数ファイル・図中の文字列検索、一括置換ができる


=== 一覧の自動生成やソースコードの自動生成がしやすい

=== ブラウザでの閲覧正

軽い　リンク



== AsciiDocの短所

=== 学習コストがかかる

AsciiDocは比較的新しいツールであり使用経験者はまだ少ないため、設計者のAsciiDocの表記法の学習コストがかかる。
また、設計者がGit等のバージョン管理ツールに慣れていない場合、学習コストがかかる。

=== 事例が少ない

AsciiDocをSIプロジェクトで導入した事例が
このため想定していない問題が発生するリスクがある。


=== 作図の柔軟性

オートシェイプで任意の作図が可能なOffice文書に比べると

=== 画像が扱いにくい

画像ファイルをディレクトリに配置し、パスをAsciiDoc内に書く
またAsciiDoc自体に画像を作成、編集する機能は無い。

=== 大きな表が扱いにくい



== 一長一短


=== 製品サポートが無い







